import { faUserSecret, faKey, faLock, faPlusCircle, faPaperPlane, faList } from '@fortawesome/free-solid-svg-icons'

export const feats = [
  {
    id: 0,
    title: 'Control your privacy',
    text: 'We don\'t save your account(s) on any central database or track your actions (only paid version).',
    icon: faUserSecret
  },
  {
    id: 1,
    title: 'Control your keys',
    text: 'Your keys are double encrypted and saved only on your device. You can import, create or delete new keys anytime. Paid version has paper export and import features.',
    icon: faKey
  },
  {
    id: 2,
    title: 'Feel safe',
    text: 'Double encryption of all keys, only one time export, needs online access only when sending transaction (cold wallet).',
    icon: faLock
  },
  {
    id: 3,
    title: 'Easy new accounts (HD Wallet)',
    text: 'Generate unlimited new accounts with one click from your main seed. It is recommended to have new account for each new transaction.',
    icon: faPlusCircle
  },
  {
    id: 4,
    title: 'Easy transactions',
    text: 'Send Ether and tokens between app wallets just by scanning the QR code.',
    icon: faPaperPlane
  },
  {
    id: 5,
    title: 'Easily test on Ethereum Test Networks',
    text: 'Test transactions on Ropsten, Kovan, Gorli or Rinkeby test networks.',
    icon: faList
  }
]

export const affiliatePrograms = [

]

export const exchangesAsAffiliate = () => [
  { name: '', affLink: '', description: '', cookieDuration: '' }
  // https://www.digitalfodder.com/bitcoin-cryptocurrency-affiliate-programs/
]

export const hardwareWallets = [

]

export const cryptoCountries = {
  Morocco: { legalStatus: 'On 20 November 2017 the exchange office issued a public statement in which it declared, "The Office des Changes wishes to inform the general public that the transactions via virtual currencies constitute an infringement of the exchange regulations, liable to penalties and fines provided for by [existing laws] in force." The following day, the monetary authorities also reacted in a statement issued jointly by the Ministry of Economy and Finance, Bank Al-Maghrib and the Moroccan Capital Market Authority (AMMC), warning against risks associated with bitcoin, which may be used "for illicit or criminal purposes, including money laundering and terrorist financing". On 19 December 2017, Abdellatif Jouahri, governor of Bank Al-Maghrib, said at a press conference held in Rabat during the last quarterly meeting of the Bank Al-Maghrib\'s Board of 2017 that bitcoin is not a currency but a "financial asset". He also warned of its dangers and called for a framework to be put in place for consumer protection.' },
  Nigeria: { legalStatus: 'As of 17 January 2017, The Central Bank of Nigeria (CBN) has passed a circular to inform all Nigerian banks that bank transactions in bitcoin and other virtual currencies have been banned in Nigeria. However, during the year, the CBN (through its Deputy Director on Banking and Payments System, Musa Itopa-Jimoh) clarified the circular and its stance on bitcoin, citing that a lot of people misinterpret the central bank’s recent warning. It noted that "Central bank cannot control or regulate bitcoin. Central bank cannot control or regulate blockchain. Just the same way no one is going to control or regulate the Internet. We don’t own it". Later on, a committee was set up by the Central Bank of Nigeria (CBN) and the Nigeria Deposit Insurance Corporation (NDIC) to look into the possibility of the country adopting the technology driving bitcoin and other digital currencies – blockchain. The committee has submitted its report but "several sub-committees are still working on the issue" according to the Director, Banking & Payments System Department at CBN, Mr. ‘Dipo Fatokun.' },
  Egypt: { legalStatus: '"Egypt’s Dar al-Ifta, the primary Islamic legislator in Egypt, has issued a religious decree classifying commercial transactions in bitcoin as haram (prohibited under Islamic law)."' },
  Algeria: { legalStatus: 'According to the "Journal Officiel" (28 December 2017): Art. 117. — The purchase, sale, use, and holding of so-called virtual currency is prohibited. Virtual currency is that used by internet users via the web. It is characterized by the absence of physical support such as coins, notes, payments by cheque or credit card. Any breach of this provision is punishable in accordance with the laws and regulations in force.' },
  'South Africa': { legalStatus: 'In December 2014 the Reserve Bank of South Africa issued a position paper on virtual currencies whereby it declared that virtual currency had ‘no legal status or regulatory framework’.[18] The South African Revenue Service classified bitcoin as an intangible asset.' },
  Canada: { legalStatus: 'Companies dealing in virtual currencies must register with the Financial Transactions and Reports Analysis Centre of Canada (Fintrac), implement compliance programs, keep the required records, report suspicious or terrorist-related transactions, and determine if any of their customers are "politically exposed persons." The law applies to non-Canadian virtual currency exchanges if they have Canadian customers. Banks may not open or maintain accounts or have a correspondent banking relationship with companies dealing in virtual currencies if that company is not registered with Fintrac. Dealers in digital currency are regulated as money services businesses. The Authorite des Marches Financiers, the regulator in the province of Quebec, has declared that some bitcoin related business models including exchanges and ATMs are regulated under its current MSB Act. As of April 2018, the Bank of Montreal (BMO) announced that it would ban its credit and debit card customers from participating in cryptocurrency purchases with their cards.[24] This is following another banking ban in Canada from Toronto Dominion (TD.)' },
  Namibia: { legalStatus: 'In September 2017 the Bank of Namibia issued a position paper on virtual currencies entitled[20] wherein it declared cryptocurrency exchanges are not allowed and cryptocurrency cannot be accepted as payment for goods and services.' },
  'United States': { legalStatus: 'The U.S. Treasury classified bitcoin as a convertible decentralized virtual currency in 2013.[26] The Commodity Futures Trading Commission, CFTC, classified bitcoin as a commodity in September 2015. Per IRS, bitcoin is taxed as a property. Bitcoin was mentioned in a U.S. Supreme Court opinion (on Wisconsin Central Ltd. v. United States) regarding the changing definition of money on 21 June 2018. If money services businesses, including cryptocurrency exchanges, money transmitters, and anonymizing services (known as "mixers" or "tumblers") do a substantial amount of business in the U.S., they are required to register with the U.S.FinCEN as a money services business design and enforce an anti-money laundering (AML) program, and keep appropriate records and make reports to FinCEN, including Suspicious Activity Reports (SARs) and Currency Transaction Reports (CTRs). Seventeen other countries have similar AML requirements.[13] As of 2018 U.S. FinCEN receives more than 1,500 SARs per month involving cryptocurrencies. In September 2016, a federal judge ruled that "Bitcoins are funds within the plain meaning of that term".[30] In June 2018, Supreme Court of the United States debated bitcoin future for the first time. Bitcoin and similar cryptocurrencies are regulated as both currency and as a security under U.S. law. Within the U.S. many states are also pursuing legislative/regulatory efforts to cover crypto instruments. Not officially Legal tender but not illegal.' },
  Mexico: { legalStatus: 'Bitcoin is legal in Mexico as of 2017. It is to be regulated as a virtual asset by the FinTech Law.' },
  Zimbabwe: { legalStatus: 'The Reserve Bank Of Zimbabwe is sceptical about bitcoin and has not officially permitted its use. On 5 April 2017 however, BitMari, a Pan-African Blockchain platform got licensed, through its banking partner, AgriBank, to operate in the country.' },
  Nicaragua: { legalStatus: 'News reports indicate that bitcoins are being used in the country.' },
  'Costa Rica': { legalStatus: 'The Costa Rican Central Bank announced that bitcoin and cryptocurrencies are not consider currencies, and are not backed by the government nor laws. However, they are not illegal. There are a few merchants who do accept bitcoins in the country.' },
  Jamaica: { legalStatus: 'The Bank of Jamaica (BoJ), the national Central Bank, has publicly declared that it must create opportunities for the exploitation of technologies including cryptocurrencies. Accordingly, in 2017 the BoJ will be embarking on a campaign to build awareness of cryptocurrencies as part of increasing general financial literacy and understanding of cryptocurrencies. Indications are that early BoJ signals point to their general framework on "electronic retail payment service systems" possibly being brought to bear on initial cryptocurrencies considerations.' },
  'Trinidad and Tobago': { legalStatus: 'Legal' },
  Argentina: { legalStatus: 'Bitcoins may be considered money, but not legal currency. A bitcoin may be considered either a good or a thing under the Argentina\'s Civil Code, and transactions with bitcoins may be governed by the rules for the sale of goods under the Civil Code.' },
  Bolivia: { legalStatus: 'Absolute ban. The Central Bank of Bolivia issued a resolution banning bitcoin and any other currency not regulated by a country or economic zone in 2014.' },
  Brazil: { legalStatus: 'Not regulated, according to a 2014 statement by the Central Bank of Brazil concerning cryptocurrencies, but is discouraged because of operational risks. In November 2017 this unregulated and discouraged status was reiterated by the Central Bank of Brazil.' },
  Chile: { legalStatus: 'There is no regulation on the use of bitcoins.' },
  Ecuador: { legalStatus: 'The Ecuadorian government has issued a ban on bitcoin and other digital currencies. The National Assembly of Ecuador banned bitcoins including other decentralized digital/crypto currencies, due to the establishment of a new state-run electronic money system. Ecuador\'s new project would be controlled by the government and tied directly to the local currency—the dollar. Users will be able to pay for select services and send money between individuals. This was slated to begin in mid-February 2015. "Electronic money is designed to operate and support the monetary scheme of dollarization," economist Diego Martinez, a delegate of the President of the Republic to the Board of Regulation and Monetary and Financial Policy.' },
  Colombia: { legalStatus: 'Financial institutions are not allowed to facilitate bitcoin transactions. The Superintendencia Financiera warned financial institutions in 2014 that they may not "protect, invest, broker, or manage virtual money operations".[' },
  Venezuela: { legalStatus: 'Bitcoin miners used to be arrested by law enforcement authorities, however in January 2018 Carlos Vargas, the government’s cryptocurrency superintendent said “It is an activity that is now perfectly legal. We have had meetings with the Supreme Court so that people who have been victims of seizures and arrests in previous years will have charges dismissed.”' },
  Kyrgyzstan: { legalStatus: 'Bitcoin is considered a commodity,[46] not a security or currency under the laws of the Kyrgyz Republic and may be legally mined, bought, sold and traded on a local commodity exchange.[47] The use of bitcoin as a currency in domestic settlements is restricted.' },
  Uzbekistan: { legalStatus: 'On September 2nd 2018, a decree legalizing crypto trading — also making it tax-free — and mining in the country came into force, making Uzbekistan a crypto-friendly state.' },
  Cyprus: { legalStatus: 'The use of bitcoins is not regulated in Cyprus.' },
  Russia: { legalStatus: 'As of November 2016 declared, bitcoins are "not illegal" according to the Federal Tax Service of Russia. Deputy Finance Minister of the Russian Federation Alexei Moiseev said in September 2017 it\'s "probably illegal" to accept cryptocurrencies payments.[51] However bitcoin market sites are blocked and in court decisions stated that bitcoin is a currency surrogate which is outlawed on the territory of Russian Federation.' },
  'United Arab Emirates': { legalStatus: 'Absolute ban. According to the Library of Congress "Under article D.7.3 of the Regulatory Framework for Stored Values and an Electronic Payment System, issued by the Central Bank of the United Arab Emirates in January 2017, all transactions in “virtual currencies” (encompassing cryptocurrencies in Arabic) are prohibited." Nevertheless, on 13 February 2018 Dubai gold trader Regal RA DMCC became the first company in the Middle East to get a license to trade cryptocurrencies, the Dubai Multi Commodities Centre said. DMCC\'s website emphasizes the "cold storage" of cryptocurrencies and states "DMCC’s Crypto-commodities license is for Proprietary Trading in Crypto-commodities only. No initial coin offerings are permitted and no establishment of an exchange is permitted under this license."' },
  Israel: { legalStatus: 'As of 2017, the Israel Tax Authorities issued a statement saying that bitcoin and other cryptocurrencies would not fall under the legal definition of currency, and neither of that of a financial security, but of a taxable asset.[55] Each time a bitcoin is sold, the seller would have to pay a capital gains tax of 25%. Miners, traders of bitcoins would be treated as businesses and would have to pay corporate income tax as well as charge a 17% VAT.' },
  'Saudi Arabia': { legalStatus: 'Financial institutions are warned from using bitcoin.[13] The Saudi Arabian Monetary Authority (SAMA) has warned from using bitcoin as it is high risk and its dealers will not be guaranteed any protection or rights.' },
  Jordan: { legalStatus: 'The government of Jordan has issued a warning discouraging the use of bitcoin and other similar systems. The Central Bank of Jordan prohibits banks, currency exchanges, financial companies, and payment service companies from dealing in bitcoins or other digital currencies. While it warned the public of risks of bitcoins, and that they are not legal tender, bitcoins are still accepted by small businesses and merchants.' },
  Lebanon: { legalStatus: 'The government of Lebanon has issued a warning discouraging the use of bitcoin and other similar systems.' },
  Turkey: { legalStatus: 'Bitcoin is not regulated as it is not considered to be electronic money according to the law.' },
  Iran: { legalStatus: 'Financial institutions are not allowed by central bank to facilitate bitcoin transactions.[13] In April 2018, Central Bank of the Islamic Republic of Iran issued a statement banning the country’s banks and financial institutions from dealing with cryptocurrencies, citing money laundering and terrorism financing risks.' },
  Bangladesh: { legalStatus: 'Financial institutions are not allowed to facilitate bitcoin transactions.[13] In September 2014, Bangladesh Bank said that "anybody caught using the virtual currency could be jailed under the country\'s strict anti-money laundering laws".' },
  India: { legalStatus: 'Finance minister Arun Jaitley, in his budget speech on 1 February 2018, stated that the government will do everything to discontinue the use of bitcoin and other virtual currencies in India for criminal uses. He reiterated that India does not recognise them as legal tender and will instead encourage blockchain technology in payment systems. "The government does not recognise cryptocurrency as legal tender or coin and will take all measures to eliminate the use of these cryptoassets in financing illegitimate activities or as part of the payments system," Jaitley said. In early 2018 India\'s central bank, the Reserve Bank of India (RBI) announced a ban on the sale or purchase of cryptocurrency for entities regulated by RBI. In 2019, a petition has been filed[by whom?] with the Supreme Court of India challenging the legality of cryptocurrencies and seeking a direction or order restraining their transaction.' },
  Nepal: { legalStatus: 'Absolute ban. On 13 August 2017 Nepal Rastra Bank declared bitcoin as illegal.' },
  Pakistan: { legalStatus: 'As of 7 April 2018, State Bank of Pakistan [SBP] has announced that bitcoin and other virtual currencies/tokens/ coins are banned in Pakistan.[13] This news was followed right after India\'s restriction of converting bitcoin and cryptocurrencies into fiat currency. For organizations and institutions it is banned by State Bank of Pakistan. Bank will not get involved if there is any dispute. They will not facilitate any transaction for it. The bank has issued an official notice on its website and has also posted the news on its official Twitter account.' },
  China: { legalStatus: 'Financial institutions are not allowed to facilitate bitcoin transactions.[13] Regulation prohibits financial firms holding or trading cryptocurrencies.[8]:China On 5 December 2013, People\'s Bank of China (PBOC) made its first step in regulating bitcoin by prohibiting financial institutions from handling bitcoin transactions. On 1 April 2014 PBOC ordered commercial banks and payment companies to close bitcoin trading accounts in two weeks. Cryptocurrency exchanges or trading platforms were effectively banned by regulation in September 2017 with 173 platforms closed down by July 2018. In early 2018 the People\'s Bank of China announced the State Administration of Foreign Exchange led by Pan Gongsheng would crack down on bitcoin mining. Many bitcoin mines in China had stopped operating by January 2018.' },
  'Hong Kong': { legalStatus: 'On 8 January 2014, the Secretary for Financial Services and the Treasury addressed bitcoin in the Legislative Council stating that "Hong Kong at present has no legislation directly regulating bitcoins and other virtual currencies of [a] similar kind. However, our existing laws (such as the Organised and Serious Crimes Ordinance) provide sanctions against unlawful acts involving bitcoins, such as fraud or money laundering." On 16 November 2013, Norman Chan, the chief executive of Hong Kong Monetary Authority (HKMA) said that bitcoins is only a virtual commodity. He also decided that bitcoins will not be regulated by HKMA. However, the authority will be closely watching the usage of bitcoins locally and its development overseas.' },
  Japan: { legalStatus: 'On 7 March 2014, the Japanese government, in response to a series of questions asked in the National Diet, made a cabinet decision on the legal treatment of bitcoins in the form of answers to the questions.[75] The decision did not see bitcoin as currency nor bond under the current Banking Act and Financial Instruments and Exchange Law, prohibiting banks and securities companies from dealing in bitcoins. The decision also acknowledges that there are no laws to unconditionally prohibit individuals or legal entities from receiving bitcoins in exchange for goods or services. Taxes may be applicable to bitcoins. As of April 2017, cryptocurrency exchange businesses operating in Japan have been regulated by the Payment Services Act. Cryptocurrency exchange businesses have to be registered, keep records, take security measures, and take measures to protect customers. Financial Services Agency (FSA) was established in 2014 for the purpose of establishing a registration platform for cryptocurrency exchange businesses. the law on cryptocurrency transactions must comply with the anti-money laundering law; and measures to protect users investors. The Payment Services Act defines “cryptocurrency” as a property value. The Act also states that cryptocurrency is limited to property values that are stored electronically on electronic devices, not a legal tender.' },
  'South Korea': { legalStatus: 'Minors and all foreigners are prohibited from trading cryptocurrencies. Adult South Koreans may trade on registered exchanges using real name accounts at a bank where the exchange also has an account. Both the bank and the exchange are responsible for verifying the customer\'s identity and enforcing other anti-money-laundering provisions.' },
  Taiwan: { legalStatus: 'Financial institutions are not allowed to facilitate bitcoin transactions.[13] Regulators have warned the public that bitcoin does not have legal protection, "as the currency is not issued by any monetary authority and is therefore not entitled to legal claims or guarantee of conversion". Financial institutions have been warned by regulators that necessary regulatory actions may be taken if they use bitcoin. On 31 December 2013, Financial Supervisory Commission (Republic of China) (FSC) and CBC issued a joint statement which warns against the use of bitcoins. It is stated that bitcoins remains highly volatile, highly speculative, and is not entitled to legal claims or guarantee of conversion. On 5 January 2014, FSC chairman Tseng Ming-chung stated that FSC will not allow the installation of bitcoin ATM in Taiwan because bitcoin is not a currency and it should not be accepted by individuals and banks as payment.' },
  Cambodia: { legalStatus: 'The National Bank of Cambodia (NBC), has "asked banks in Cambodia not to allow people to conduct transactions with cryptocurrencies."' },
  Indonesia: { legalStatus: 'On 7 December 2017, Bank Indonesia, the country\'s central bank, issued a regulation banning the use of cryptocurrencies including bitcoin as payment tools starting 1 January 2018.' },
  Malaysia: { legalStatus: 'On 4 November 2013, Bank Negara Malaysia (BNM) met with local bitcoin proponents to learn more about the currency but did not comment at the time.[81] BNM issued a statement on 6 January 2014 that bitcoin is not recognised as a legal tender in Malaysia. The central bank will not regulate bitcoin operations at the moment and users should aware of the risks associated with bitcoin usage.' },
  Philippines: { legalStatus: 'On 6 March 2014, Bangko Sentral ng Pilipinas (BSP) issued a statement on risks associated with bitcoin trading and usage. Recently virtual currencies were legalized and cryptocurrency exchanges are now regulated by Central Bank of the Philippines (Bangko Sentral ng Pilipinas) under Circular 944; however bitcoin and other "virtual currencies" are not recognized by the BSP as currency as "it is neither issued or guaranteed by a central bank nor backed by any commodity."' },
  Singapore: { legalStatus: 'In December 2013, the Monetary Authority of Singapore reportedly stated that "[w]hether or not businesses accept bitcoins in exchange for their goods and services is a commercial decision in which MAS does not intervene." On 22 September 2013, the Monetary Authority of Singapore (MAS) warned users of the risks associated with using bitcoin stating "If bitcoin ceases to operate, there may not be an identifiable party responsible for refunding their monies or for them to seek recourse"[85] and in December 2013 stated "Whether or not businesses accept Bitcoins in exchange for their goods and services is a commercial decision in which MAS does not intervene"[86] In January 2014, the Inland Revenue Authority of Singapore issued a series of tax guidelines according to which bitcoin transactions may be treated as a barter exchange if it is used as a payment method for real goods and services. Businesses that deal with bitcoin currency exchanges will be taxed based on their bitcoin sales. In April 2019, the MAS referred to bitcoin as a digital payment token for purposes of the Payment Services Act.' },
  Thailand: { legalStatus: 'The initial position of the Bank of Thailand, mid 2013, was to discourage the use of bitcoin, however as of 2017, the Bank of Thailand is open to bitcoin provided proper controls are in place. Thai based bitcoin exchanges can only exchange Digital Currencies for Thai Baht and are required to operate with a Thailand Business Development Department e-commerce license. They are also required to have KYC and CDD policies and procedures in place, in accordance with the Ministerial Regulation Prescribing Rules and Procedures for Customer Due Diligence, Reference Page 8 Volume 129 Part 44 A Government Gazette 23 May 2555 (2012). Suspicious activity must be reported to the Anti-Money Laundering Office (Thailand) (AMLO), of Thailand. The SEC Thailand encourages access to funding for businesses, including high potential tech startups, and realizes the potential of ICO in answering startups’ funding needs. In cases where an ICO constitutes offering of securities, the issuer will need to comply with applicable regulatory requirements. The SEC Thailand issued a Public Consultation Document Aor Tor Ngor 34/2560 27 October 2017 Topic: Regulatory approach on Initial Coin Offering (ICO). As of February 2018 the Thai central bank has prohibited financial institutions in the country from five key cryptocurrency activities. These include 1) Investing or trading in cryptocurrency 2) Exchanging cryptocurrencies 3) Creating platforms for cryptocurrency trading 4) Allowing clients to use credit cards to buy cryptocurrencies 5) Advising customers on cryptocurrency investing and trading. Banks complying with these new rules include Bangkok Bank, SIAM Commercial Bank and Krungsri.' },
  Vietnam: { legalStatus: 'Trading in bitcoin in Vietnam is still unrestricted and unregulated by law, and two largest bitcoin markets in Vietnam - VBTC and Bitcoin Vietnam are working without being restricted. In August 2017, Vietnam\'s prime minister has approved a plan that could see the country formally recognize bitcoin as a form of payment by the end of 2018. The State Bank of Vietnam has declared that the issuance, supply and use of bitcoin and other similar virtual currency is illegal as a mean of payment and subject to punishment ranging from 150 million to 200 million VND,[93] but the government doesn\'t ban bitcoin trading as a virtual goods or assets.' },
  Brunei: { legalStatus: 'Bitcoin and cryptocurrency is not legal tender in Brunei Darussalam and are not regulated by AMBD (Brunei Monetary Authority). It is not protected under the laws administered by AMBD (Brunei Monetary Authority). AMBD however, advised the public not to be easily enticed by any investment or financial activity advertisements, and to conduct due diligence and understand the financial products properly before participating. There is no law that stated that holding or trading bitcoin is illegal.' },
  Austria: { legalStatus: 'Not considered to be an official form of currency, earnings are subject to tax law. The Financial Market Authority (FMA) has warned investors that cryptocurrencies are risky and that the FMA does not supervise or regulate virtual currencies, including bitcoin, or cryptocurrency trading platforms.' },
  Croatia: { legalStatus: 'Croatia’s Financial Stability Council warned investors about the risks of virtual currencies, such as digital wallet theft and fraud, on December 18, 2017. The National Bank of Croatia issued a similar warning on September 22, 2017.' },
  'Czech Republic': { legalStatus: 'Businesses and individuals who buy, sell, store, manage, or mediate the purchase or sale of virtual currencies or provide similar services must comply with the anti-money laundering law. Bitcoin is classified as intangible asset (not as electronic money) for the purpose of accounting and taxes.' },
  Germany: { legalStatus: 'On 19 August 2013, the German Finance Ministry announced that bitcoin is now essentially a "unit of account" and can be used for the purpose of tax and trading in the country, meaning that purchases made with it must pay VAT as with euro transactions. It is not classified as a foreign currency or e–money but stands as "private money" which can be used in "multilateral clearing circles", according to the ministry. The Bundesbank says that bitcoin is not a virtual currency or digital money. It recommends using the term “crypto token.”' },
  Hungary: { legalStatus: 'The Hungarian Central Bank, Magyar Nemzeti Bank (MNB) has issued several warnings over cryptocurrencies, stating that it’s “much riskier” than other electronic payments such as credit cards.' },
  Poland: { legalStatus: 'The use of bitcoin in Poland is not regulated by a legal act at present. Szymon Woźniak of the Ministry of Finance made an official announcement on the legality of bitcoin on 18 December 2013 at a conference at the Warsaw School of Economics stating that the Ministry of Finance does not consider bitcoin illegal and does not want to hinder its development.[101] He clarified that while not illegal, bitcoin cannot be considered legal tender, and, in the light of the directives of the European Union, it is neither electronic money.[101] As of 27 January 2015, several banks have closed accounts of clients trading bitcoin, and indicated "presumption of criminal offense" as the cause, with "criminal offense" presumably being "cryptocurrency trade".[102] As of 7 July 2017, the National Bank of Poland (NBP) and Financial Supervision Authority (KNF) issued a comment on virtual "currencies".[103] They underlined that virtual currencies (including bitcoin): (1) are not issued or guaranteed by the central bank, (2) are not money, i.e. they are neither legal tender nor currency, (3) can not be used to pay tax liabilities, (4) do not meet the criterion of universal acceptability in shopping and service points, (5) are not electronic money, (6) are not payment services (in legal terms), (7) are not financial instruments (in legal terms). They added that trading virtual currencies in Poland does not violate national or EU law, however, having virtual "currencies", involves many risks: (1) risk related to the possibility of loss of funds due to theft, (2) risk related to lack of guarantee, (3) risk of lack of universal acceptability, (4) risk related to the possibility of fraud, (5) risk of high price change. Because of these risks, the NBP and KNF warn against buying virtual currencies and investing in them. The NBP and KNF recognize that the purchase, possession and sale of virtual currencies by entities supervised by the KNF (e.g. banks) would be burdened with high risk and would not ensure a stable and prudent management of the financial institution. Financial institutions should be cautious about engaging and cooperating with virtual currency "trading" entities.' },
  Romania: { legalStatus: 'As of March 2015, an official statement of the Romanian National Bank mentioned that "using digital currencies as payment has certain risks for the financial system". In October 2017, the National Fiscal Administration Agency (ANAF) declared that there is a lack of a legislative framework around bitcoin, and therefore, it is unable to create a tax regulation framework for it as well (implying no taxation). In January 2019, Law nr. 30/2019 clarifies that starting in 2019, income from trading "virtual currency" is classified under "income from other sources". In addition, there is a new subpoint, Article 116. (2) c), specifying that the income tax of 10% is only applied on the "positive difference between the selling price and acquisition price" (and not to the entire received amount from a sale). In addition, profits under 200 RON per transaction that total under 600 RON during a fiscal year are exempt from tax.' },
  Slovakia: { legalStatus: 'The National Bank of Slovakia (NBS), stated[107] that bitcoin does not have the legal attributes of a currency, and therefore does not fall under national control.[note 1] European legislation, including the Slovak law, does not define the activities associated with virtual currency. Such activities are not regulated and supervised by the National Bank of Slovakia or the European Central Bank. At the same time NBS points out that any legal person or natural person in the Slovak Republic shall not issue any notes or any other coins. Unlawful manufacturing of banknotes and coins and putting them into circulation is punishable by law. In this context, NBS points out that virtual currencies have not a physical counterpart in the form of legal tender and participation in such a scheme (virtual currency) is at your own risk. Exchanges or purchases of virtual currencies represent the business risk of investors and investors\' money are not protected. For any compensation of losses caused by such exchanges or purchases there is no legal entitlement.' },
  Slovenia: { legalStatus: 'On 23 December 2013 the Slovenian Ministry of Finance made an announcement[108] stating that bitcoin is neither a currency nor an asset. There is no capital gains tax chargeable on bitcoin, however bitcoin mining is taxed and businesses selling goods/services in bitcoin are also taxed.' },
  Switzerland: { legalStatus: 'Bitcoin businesses in Switzerland are subject to anti-money laundering regulations and in some instances may need to obtain a banking license. On 5 December 2013, a proposal was put forth by 45 members of the Swiss Parliament for digital sustainability (Pardigli), that calls on the Swiss government to evaluate the opportunities for utilization of bitcoin by the country’s financial sector.[110] It also seeks clarification on bitcoin’s legal standing with respect to VAT, securities and anti-money laundering laws. In response to the parliament postulates, the Swiss Federal Council issued a report on virtual currencies in June 2014.[112] The report states that since virtual currencies are not in a legal vacuum, the Federal Council has concluded that there is no need for legislative measures to be taken at the moment. In 2016, Zug added bitcoin as a means of paying city fees, in a test and an attempt to advance Zug as a region that is advancing future technologies.[113] Swiss Federal Railways, government-owned railway company of Switzerland, sells bitcoins at its ticket machines.' },
  Belarus: { legalStatus: 'The Decree On the Development of Digital Economy — the decree of Alexander Lukashenko, the President of the Republic of Belarus, which includes measures to liberalize the conditions for conducting business in the sphere of high technologies. The provisions of the decree "On the Development of Digital Economy" create of a legal basis for the circulation of digital currencies and tokens based on blockchain technology, so that resident companies of the High-Tech Park can provide the services of stock markets and exchange offices with cryptocurrencies and attract financing through the ICO. For legal entities, the Decree confers the rights to create and place their own tokens, carry out transactions through stock markets and exchange operators; to individuals the Decree gives the right to engage in mining, to own tokens, to acquire and change them for Belarusian rubles, foreign currency and electronic money, and to bequeath them. Up to 1 Jan In 2023, the Decree excludes revenue and profits from operations with tokens from the taxable base. In relation to individuals, the acquisition and sale of tokens is not considered entrepreneurial activity, and the tokens themselves and income from transactions with them are not subject to declaration. The peculiarity of the introduced regulation is that all operations will have to be carried out through the resident companies of the High Technology Park' },
  Ukraine: { legalStatus: 'The use of bitcoins is not regulated in Ukraine. Mining is legal type of entrepreneurship.' },
  Denmark: { legalStatus: 'Denmark’s Financial Supervisory Authority issued a statement declaring that bitcoin is not a currency and stating that it will not regulate its use. On 17 December 2013, Denmark\'s Financial Supervisory Authority (FSA) has issued a statement that echoes EBA\'s warning. As of 2017, FSA says that doing business with bitcoin does not fall under its regulatory authority and therefore FSA does not prevent anyone from opening such businesses. FSA\'s chief legal adviser says that Denmark might consider amending existing financial legislation to cover virtual currencies.' },
  Estonia: { legalStatus: 'In Estonia, the use of bitcoins is not regulated or otherwise controlled by the government. The Estonian Ministry of Finance have concluded that there is no legal obstacles to use bitcoin-like crypto currencies as payment method. Traders must therefore identify the buyer when establishing business relationship or if the buyer acquires more than 1,000 euros of the currency in a month.' },
  Finland: { legalStatus: 'The Finnish Tax Administration has issued instructions for the taxation of virtual currencies, including the bitcoin.[3]:Finland[118] Rather than a currency or a security, a bitcoin transaction is considered a private contract equivalent to a contract for difference for tax purposes. Purchases of goods with bitcoin or conversion of bitcoin into legal currency "realizes" the value and any increase in price will be taxable; however, losses are not tax-deductible. Mined bitcoin is considered earned income. Ruling 034/2014 by the Finnish Central Board of Taxes (CBT) stated that commission fees charged on bitcoin purchases by an exchange market were, under the EU VAT Directive, banking services and therefore VAT exempt. This is because the court classified bitcoins as payment instruments - whereas most countries treat their use as an unregulated method for the exchange of goods, or even as a crime.' },
  Iceland: { legalStatus: 'According to a 2014 opinion, from the Central Bank of Iceland "there is no authorization to purchase foreign currency from financial institutions in Iceland or to transfer foreign currency across borders on the basis of transactions with virtual currency. For this reason alone, transactions with virtual currency are subject to restrictions in Iceland."[121] This does not stop[122] businesses in Iceland from mining bitcoins.[123] The Icelandic Central Bank confirmed that "it is prohibited to engage in foreign exchange trading with the electronic currency bitcoin, according to the Icelandic Foreign Exchange Act". On 12 March 2017, the Central Bank amended its rules. With the new rules, wide and general exemptions have been granted from the restrictions of the Foreign Exchange Act No. 87/1992' },
  Lithuania: { legalStatus: 'Bank of Lithuania released a warning on 31 January 2014, that bitcoin is not recognized as legal tender in Lithuania and that bitcoin users should be aware of high risks that come with the usage of it.' },
  Norway: { legalStatus: 'The Norwegian Tax Administration stated in December 2013 that they don\'t define bitcoin as money but regard it as an asset. Profits are subjected to wealth tax. In business, use of bitcoin falls under the sales tax regulation. The Norwegian government stated in February 2017 that they would not levy VAT on the purchase or sale of bitcoin.' },
  Sweden: { legalStatus: 'The Swedish Tax Agency has given a preliminary ruling on Value Added Tax (VAT) on bitcoins, stating that trade in bitcoins is not subject to Swedish VAT, but is instead subject to the Finansinspektionen (Financial Supervisory Authority) regulations and treated as a currency. The decision has been appealed by the Swedish Tax Authority. The Swedish jurisdiction is in general quite favorable for bitcoin businesses and users as compared to other countries within the EU and the rest of the world. The governmental regulatory and supervisory body Swedish Financial Supervisory Authority (Finansinspektionen) have legitimized the fast growing industry by publicly proclaiming bitcoin and other digital currencies as a means of payment. For certain businesses interacting with fiat (mainly exchanges) the current regulation dictates that an application for approval/license must be filed and all the AML/CTF and KYC regulations applicable to more traditional financial service providers must be followed.' },
  'Bosnia and Herzegovina': { legalStatus: 'No regulation on the use of bitcoins.' },
  Bulgaria: { legalStatus: 'There is not a single word in Bulgarian laws about bitcoin. People owe 10% tax if they made profit trading.' },
  Greece: { legalStatus: 'No specific legislation on bitcoins exists in Greece.' },
  Italy: { legalStatus: 'Italy does not regulate bitcoin use by private individuals.' },
  Malta: { legalStatus: 'As of 2017, Malta does not have any regulations specifically pertaining to bitcoins.[3]:Malta In 2017, the country’s prime minister Joseph Muscat announced the approval of a national strategy to promote bitcoin and blockchain technology. Muscat specifically addressed the bitcoin blockchain’s ability to handle, store and process sensitive data in an immutable and decentralized ecosystem.' },
  Macedonia: { legalStatus: 'No specific legislation on bitcoins or cryptocurrency exists in Macedonia. In 2016 the National Bank of Republic of Macedonia published a press release regarding an investigation it made into ONECOIN, and discouraged the citizens from investing in it since it was most likely a scam. In the same press release the NBRM quoted the law on Foreign Exchange Operations, but since cryptocurrencies do not constitute a foreign currency as they are quoted by the law, it leaves them unregulated. The only legal tender for payment in the country is the Macedonian Denar, which means payment with any other regular or crypto currency is prohibited.' },
  Portugal: { legalStatus: 'Bitcoin has no specific legal framework in Portugal.' },
  Spain: { legalStatus: 'Transactions in bitcoins are subject to the same laws as barter transactions.' },
  Belgium: { legalStatus: 'The Minister of Finance indicated that government intervention with regard to the bitcoin system does not appear necessary at the present time' },
  France: { legalStatus: 'The French Ministry of Finance issued regulations on 11 July 2014 pertaining to the operation of virtual currency professionals, exchanges, and taxation.' },
  Ireland: { legalStatus: 'The Central Bank of Ireland was quoted in the Assembly of Ireland as stating that it does not regulate bitcoins.' },
  Luxembourg: { legalStatus: 'The Commission de Surveillance du Secteur Financier has issued a communication in February 2014 acknowledging the status of currency to the bitcoin and other cryptocurrencies.[132] The first BitLicence was issued in October 2015,[133] and the government is actively supporting this development.' },
  Netherlands: { legalStatus: 'As of 2017, virtual currencies such as bitcoin do not fall within the scope of the Act on Financial Supervision of the Netherlands.' },
  'United Kingdom': { legalStatus: 'As of 2017, the government of the United Kingdom has stated that bitcoin is unregulated and that it is treated as a \'foreign currency\' for most purposes, including VAT/GST. Bitcoin is treated as \'private money\'. When bitcoin is exchanged for sterling or for foreign currencies, such as euro or dollar, no VAT will be due on the value of the bitcoins themselves. However, in all instances, VAT will be due in the normal way from suppliers of any goods or services sold in exchange for bitcoin or other similar cryptocurrency. Profits and losses on cryptocurrencies are subject to capital gains tax. An industry body called “CryptoUK” are aiming to improve the industry standards around Bitcoin. They have proposed a code of conduct that includes the provision of Anti-Money Laundering and extra security measures.' },
  Australia: { legalStatus: 'In December 2013, the governor of the Reserve Bank of Australia (RBA) indicated in an interview about bitcoin legality stating, "There would be nothing to stop people in this country deciding to transact in some other currency in a shop if they wanted to. There’s no law against that, so we do have competing currencies."[136] Australia has officially confirmed it will treat bitcoin “just like money” on 1 July 2017 and it will no longer be subject to double taxation.[citation needed] Beginning in April 2018, Australian digital currency exchanges must register with the Australian Transaction Reports and Analysis Centre and implement "know your customer" policies to comply with new anti-money laundering legislation.' },
  'New-Zealand': { legalStatus: 'The Reserve Bank of New Zealand states: "Non-banks do not need our approval for schemes that involve the storage and/or transfer of value (such as ‘bitcoin’) – so long as they do not involve the issuance of physical circulating currency (notes and coins)."' }
}
